### ISSUE TITLE
Merge config_defaults:cloud_init into machines:vm_name:cloud_init

### ISSUE THREAD

**Issue by memblin** [memblin/tkc-lvlab-py#19]
As a user of lvlab I need the ability to have different cloud-init runcmd settings across machines.

- Blocking #20 

## Approach

Merge the machines cloud_init configuration section into the config_defaults cloud_init section so that the resulting cloud_init config is a merged dict with any matching keys in the config_defaults section being overridden by machine values. If possible, lists should be appended, config_defaults > machine so that the we can rely on config_defaults items being run first before machine direct items.

This should also fix `cloud_init:mounts` but it won't address the similar issue that exists with `config_defaults:shared_directories`. We'll address that feature in a separate issue.

## Example: 

 - Using runcmd to download an internal or private CA is something all machines in a manifest would probably want to do so this works well in the config_defaults cloud-init section.
 - Something like installing a salt controller using the Salt bootstrap installer would normally only happen on one or two machines in a local testing lab scenario

```yaml
environment:
  - name: libvirt-salt-dev
    libvirt_uri: qemu:///system
    config_defaults:
      domain: local
      os: fedora40
      cpu: 2
      memory: 2048
      disks:
        - name: primary
          size: 25G
      interfaces:
          network: default
          nameservers:
            search: [local]
            addresses: [192.168.122.1]
      shared_directories:
        - source: /home/crow/repos
          mount_tag: gitrepos
      cloud_init:
        user: root
        pubkey: ~/.ssh/id_ed25519.pub
        sudo: ["ALL=(ALL) NOPASSWD:ALL"]
        shell: /bin/bash
        runcmd:
          - curl --insecure https://vault.tkclabs.io:8200/v1/root_ca/ca/pem > /etc/pki/ca-trust/source/anchors/vault.tkclabs.io.crt

    machines:
      - vm_name: salt.local
        hostname: salt
        interfaces:
          - name: eth0
            ip4: 192.168.122.12/24
            ip4gw: 192.168.122.1
        cloud_init:
          runcmd:
            - curl -s -o /root/bootstrap-salt.sh -L https://bootstrap.saltproject.io
            - chmod 0755 /root/bootstrap-salt.sh
            - /root/bootstrap-salt.sh -X -M -A 127.0.0.1 stable 3007
            # This reduces latency for some salt operations when reverse
            # DNS is not in place for the machine.
            - |
              cat << EOF > /etc/salt/minion.d/disable_fqdns_grains.conf
              enable_fqdns_grains: False
              EOF
            - systemctl start salt-master
            - systemctl start salt-minion
          mounts:
            - [ gitrepos, /srv/git, virtiofs, "rw,relatime 0 0" ]
```

## AC

- Cloud-init configs are merged in a way that ensures each machine can have customized on-boot actions
- Runcmd operations defined in config_defaults cloud_init section should execute before those defined in the machines cloud_init section.
