### ISSUE TITLE
Merge config_defaults:shared_directories with machine:shared_directories

### ISSUE THREAD

**Issue by memblin** [memblin/tkc-lvlab-py#20]
As a user of lvlab I need the ability to have different shared_directories settings across machines.

## Approach

Merge the machines shared_directories configuration section into the config_defaults shared_directories section so that the resulting shared_directories config is a merged dict with any matching keys in the config_defaults section being overridden by machine values.

## Example: 

 - All machines should mount /srv/data in read-only mode
 - Only the salt.local machine should mount /home/repos/crow in read-write mode
 
```yaml
environment:
  - name: libvirt-salt-dev
    libvirt_uri: qemu:///system
    config_defaults:
      domain: local
      os: fedora40
      cpu: 2
      memory: 2048
      disks:
        - name: primary
          size: 25G
      interfaces:
          network: default
          nameservers:
            search: [local]
            addresses: [192.168.122.1]
      shared_directories:
        - source: /srv/data
          mount_tag: datadir
      cloud_init:
        user: root
        pubkey: ~/.ssh/id_ed25519.pub
        sudo: ["ALL=(ALL) NOPASSWD:ALL"]
        shell: /bin/bash
        runcmd:
          - curl --insecure https://vault.tkclabs.io:8200/v1/root_ca/ca/pem > /etc/pki/ca-trust/source/anchors/vault.tkclabs.io.crt
        mounts:
          - [ datadir, /srv/data, virtiofs, "ro,relatime 0 0" ]

    machines:
      - vm_name: salt.local
        hostname: salt
        interfaces:
          - name: eth0
            ip4: 192.168.122.12/24
            ip4gw: 192.168.122.1
        shared_directories:
          - source: /home/crow/repos
            mount_tag: gitrepos
        cloud_init:
          runcmd:
            - curl -s -o /root/bootstrap-salt.sh -L https://bootstrap.saltproject.io
            - chmod 0755 /root/bootstrap-salt.sh
            - /root/bootstrap-salt.sh -X -M -A 127.0.0.1 stable 3007
            # This reduces latency for some salt operations when reverse
            # DNS is not in place for the machine.
            - |
              cat << EOF > /etc/salt/minion.d/disable_fqdns_grains.conf
              enable_fqdns_grains: False
              EOF
            - systemctl start salt-master
            - systemctl start salt-minion
          mounts:
            - [ gitrepos, /srv/git, virtiofs, "rw,relatime 0 0" ]
      - vm_name: ghar.local
        hostname: ghar
        interfaces:
          - name: eth0
            ip4: 192.168.122.17/24
            ip4gw: 192.168.122.1
```

## AC

- Each machine can have a individual shared_directories configuration.
- If there is no config_defaults:shared_directories and no machine:shared_directories then shared memory should not be enabled for that machine; it's required only on machines that use shared host directories.
- cloud_init:mounts should be fixed by #19 but validate that this is correct after shared_directories is updated
