### ISSUE TITLE
Make shared_directories option work on a per-VM basis

### ISSUE THREAD

**Issue by memblin** [memblin/tkc-lvlab-py#47]
While attempting to work on a  salt-master deployment I needed to mount some host machine directories on the Salt server for access via GitFS.  I didn't want the host machine directories mounted on all VMs though just the one running Salt.

However it seems like the config is only picked up when added to the `config_defaults` section of the Lvlab.yml

When I had the values set directly under the salt machine I had defined it was not mounted. When I added it to the `config_defaults` it worked as expected.

This section of the `utils.libvirt` module is what adds the flags to our `virt-install` command when the values are set in `config_defaults`:

- https://github.com/memblin/tkc-lvlab-py/blob/a85fa52489cef0e6d4400c2413c18bb106e63cde/tkc_lvlab/utils/libvirt.py#L253-L259 

This should be adjusted to pickup the shared directories from a per-machine config basis too.

## Non-Working

```yaml
---
environment:
  - name: labsalt
    libvirt_uri: qemu:///system
    config_defaults:
      domain: local
      os: debian12
      cpu: 2
      memory: 2048
      disks:
        - name: primary
          size: 25G
      interfaces:
        network: default
        nameservers:
          search: [local]
          addresses: [192.168.122.1]
      cloud_init:
        user: root
        pubkey: ~/.ssh/id_ed25519.pub
        sudo: ["ALL=(ALL) NOPASSWD:ALL"]
        shell: /bin/bash

    machines:
      - vm_name: salt-01-labsalt-lo-local
        hostname: salt-01-labsalt-lo-local
        fqdn: salt-01.labsalt.lo.local
        os: debian12
        interfaces:
          - name: enp1s0
            ip4: 192.168.122.10/24
            ip4gw: 192.168.122.1
        shared_directories:
          - source: /home/crow/repos/github/
            mount_tag: gitrepos
        cloud_init:
          mounts:
            - [gitrepos, /srv/git, virtiofs, "ro,relatime"]
```

## Working

```yaml
---
environment:
  - name: labsalt
    libvirt_uri: qemu:///system
    config_defaults:
      domain: local
      os: debian12
      cpu: 2
      memory: 2048
      disks:
        - name: primary
          size: 25G
      interfaces:
        network: default
        nameservers:
          search: [local]
          addresses: [192.168.122.1]
      shared_directories:
        - source: /home/crow/repos/github/
          mount_tag: gitrepos
      cloud_init:
        user: root
        pubkey: ~/.ssh/id_ed25519.pub
        sudo: ["ALL=(ALL) NOPASSWD:ALL"]
        shell: /bin/bash

    machines:
      - vm_name: salt-01-labsalt-lo-local
        hostname: salt-01-labsalt-lo-local
        fqdn: salt-01.labsalt.lo.local
        os: debian12
        interfaces:
          - name: enp1s0
            ip4: 192.168.122.10/24
            ip4gw: 192.168.122.1
        cloud_init:
          mounts:
            - [gitrepos, /srv/git, virtiofs, "ro,relatime"]
```
